apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-app.fullname" . }}-app-config
  labels:
  {{- include "flask-app.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.appConfig.appName | quote }}
