apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "flask-app.fullname" . }}-pv
  labels:
  {{- include "flask-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: {{ .Values.pv.hostPath }}
  storageClassName: {{ .Values.pv.storageClassName }}
