apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flask-app.fullname" . }}-pvc
  labels:
  {{- include "flask-app.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest | quote }}
  storageClassName: {{ .Values.pvc.storageClass | quote }}
