apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-app.fullname" . }}-app-secret
  labels:
  {{- include "flask-app.labels" . | nindent 4 }}
stringData:
  API_KEY: {{ required "appSecret.apiKey is required" .Values.appSecret.apiKey |
    quote }}
type: Opaque
